scss:
  config_file: config/hound/.scss-style.yml

ruby:
  config_file: config/hound/.ruby-style.yml

# javascript:
# ignore_file: .javascript_ignore

javascript:
  enabled: false

coffeescript:
  config_file: config/hound/.coffeescript-style.json

fail_on_violations: true