scss:
  config_file: .scss-style.yml

ruby:
  config_file: .ruby-style.yml

javascript:
  enabled: false
  #ignore_file: .javascript_ignore

coffeescript:
  config_file: .coffeescript-style.json

fail_on_violations: true
