require 'test_helper'

class SlugTest < Capybara::Rails::TestCase
  test 'undefined _slug is autogenerated based on specified configuration' do
    book = Book.create(title: 'The Art of War')
    assert_equal('the-art-of-war', book.slug)
  end

  test 'defined _slug should be used as default' do
    author = Author.create(name: 'Lara Croft')
    defined_slug = 'lara-croft-defined'
    author._slug = defined_slug
    author.save
    assert_equal(defined_slug, author.slug)
  end

  test 'empty _slug should be autogenerated based on specified configuration' do
    author = Author.create(name: 'Lara Croft')
    author._slug = ''
    author.save
    assert_equal('lara-croft', author.slug)
  end

  test 'changed slug configuration field should use _slug if _slug is defined' do
    author = Author.create(name: 'Lara Croft', nickname: 'Lucky')
    author._slug = 'lara-croft'
    author._slugs = ['lucky']
    author.save
    assert_equal('lara-croft', author.slug)
  end
end